#TODO 1: Importing all the required classes and files
from flask import Flask, request
import database

#TODO 2: Create instance of Flask class for web App
#__name__ is contain string '__main__' value,when we run script
app = Flask(__name__)

#TODO 3: GET call method for events,get all the events from DB generated by Github repository
@app.route('/events')
def getEvents():
   #return all database records to UI
   return database.find({}),200

#TODO 4: POST call method for generate event and store it to DB
@app.route('/github-webhook',methods = ['POST', 'GET'])
def postPayloadToDatabase():
   if request.method == 'POST':
      #storing request.json to payload
      payload = request.json
      print(payload)
      #store/push the action to the DB
      database.insert(payload)
      #print the running status on UI
      return "Its working", 200
   else:
      return "Its not working ", 200

#TODO 5: Run the App and print all possible errors if it generated
if __name__ == '__main__':
   app.run(debug = True)